### PR TITLE
View engine

### PR DESCRIPTION
**Pull request by MynahMarie**
I initiliazed the view engine and modified the router to render the home page. Also created a helpers folder with an index.js file where we can eventually place our helper functions. Also modified the articles.hbs to use the keys that will be returned by the data object.

### CODE REVIEW

**Comment by Karyum** [comment]
@ghassanmas @prodionov Instead being a pain in the a** you two you could do stuff like reviewing this pull request

**Comment by harrygfox** [comment]
@MynahMarie Please resolve merge conflicts and re-assign to Mario and Claire and we'll get this merged in! 🍸 ☕️

**Comment by harrygfox** [comment]
More conflicts, unfortunately, @MynahMarie! Moving target much!

**Comment by prodionov** [comment]
The pull request#26 has the later version, i.e. this pull request is not relevant anymore

**Pull request closed without merging**
